{
 "title": "Spin Master",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Run parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spinmaster_service_params",
     "select": [
      [
       { "params": [ "fm_target_temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "spinmaster_service_params",
     "select": [
      [
       { "params": [ "reservoir_target_temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "spinmaster_service_params",
     "select": [
      [
       { "params": [ "flow_rate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "spinmaster_service_params",
     "select": [
      [
       { "params": [ "run_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Optical Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Polarization meter Thor Labs (PAX1000)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Azimuth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "polarimeter_logfmt",
     "select": [
      [
       { "params": [ "azimuth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Ellipticity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "polarimeter_logfmt",
     "select": [
      [
       { "params": [ "ellipticity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DOP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "polarimeter_logfmt",
     "select": [
      [
       { "params": [ "DOP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "FM left (Thermistor 0)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "thermistor 0" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FM right (Thermistor 1)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Separation chamber (Thermistor 2)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reservoir Heater (Thermistor 3)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Separation chamber (All)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "SOLUTION TEMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FM LEFT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FM RIGHT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reservoir",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SOLUTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "query": "SELECT last(\"value\")  / 1000 FROM \"exe_thermistors_logfmt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HEATER",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exe_thermistors_logfmt",
     "select": [
      [
       { "params": [ "Tc_thermistor3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}